override HOST_PRIMARY_ARCH := host_x86_64
override HOST_32BIT_ARCH := host_i386
override HOST_FORCE_32BIT := -m32
override TARGET_PRIMARY_ARCH := target_armhf
override TARGET_SECONDARY_ARCH := 
override TARGET_ALL_ARCH :=  target_armhf 
override TARGET_FORCE_32BIT := 
override SUPPORT_SHADOW_FREELISTS := 1
override METAG_VERSION_NEEDED := 2.8.1.0.3
override MIPS_VERSION_NEEDED := 2014.07-1
override KERNELDIR := /home/wraith/build/linux/v4.4/
override KERNEL_ID := 4.4.22
override PVRSRV_MODULE_BASEDIR := /lib/modules/4.4.22/extra/
override KERNEL_COMPONENTS := srvkm drm_nulldisp
override EXTRA_PVRSRVKM_COMPONENTS := dbgdrv
override KERNEL_CROSS_COMPILE := arm-linux-gnueabihf-
override PVRSRV_MODNAME := pvrsrvkm
override PVR_BUILD_DIR := nohw_linux
override PVR_BUILD_TYPE := release
override DISPLAY_CONTROLLER := drm_nulldisp
override PVR_SYSTEM := rgx_nohw
override PVR_LOADER := 
override BUILD := release
override DEBUGLINK := 1
override PDUMP := 1
override SUPPORT_COMPUTE := 1
override SUPPORT_MIPS_FIRMWARE := 1
override RGX_TIMECORR_CLOCK := mono
override PVR_HANDLE_BACKEND := idr
override SUPPORT_SERVER_SYNC := 1
override SUPPORT_BUFFER_SYNC := 1
